introduction:
  title: Introduction
quickStart:
  title: Quick Start
querying:
  title: Writing Queries
  criteria: Query Criteria
  pagination: Pagination
  ordering: Ordering
  projections: Query Projections
  joinQueries: Join Queries
  explicitQueries: Explicit Queries
  nativeQueries: Native Queries
dataUpdates:
  title: Updating Data
  transactions: Transactions
  batchUpdates: Batch Updates
  batchDeletes: Batch Deletes
  timestamps: Entity Timestamps
howItWorks:
  title: How Predator Works
spring:
  title: Spring Integration
jpa:
  title: Predator with JPA
sql:
  title: Predator with SQL
