introduction:
  title: Introduction
quickStart:
  title: Quick Start
repositories:
  title: Repository Interfaces
querying:
  title: Writing Queries
  criteria: Query Criteria
  pagination: Pagination
  ordering: Ordering
  projections: Query Projections
  dto: DTO Projections
  joinQueries: Join Queries
  explicitQueries: Explicit Queries
  nativeQueries: Native Queries
  async: Asynchronous Queries
  reactive: Reactive Queries
dataUpdates:
  title: Updating Data
  transactions: Transactions
  batchUpdates: Batch Updates
  batchDeletes: Batch Deletes
  timestamps: Entity Timestamps
howItWorks:
  title: How Predator Works
spring:
  title: Spring Data Support
sql:
  title: Predator with SQL
  jdbc:
    title: Predator JDBC
    jdbcQuickStart: JDBC Quick Start
    jdbcConfiguration: JDBC Configuration
    jdbcRepositories: JDBC Repositories
    sqlMapping: Mapping Entities
    jdbcJoinQueries: JDBC Join Queries
    jdbcDataTypes: JDBC Data Types
    jdbcNativeQueries: Explicit JDBC Queries

