name: Documentation
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Deploy
      uses: micronaut-projects/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BASE_BRANCH: master 
        BRANCH: gh-pages 
        FOLDER: build/docs
        BUILD_SCRIPT: ./gradlew docs

